version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=alejo
      - POSTGRES_PASSWORD=alejandrots11
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=diegosarmientoq1245@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=alejandrots11
    ports:
      - 5050:80

